//
//  UIColor+RNSAdditions.swift
//
//  Generated by Zeplin on 11/21/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var rnsWildStrawberry: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 50.0 / 255.0, blue: 158.0 / 255.0, alpha: 1.0)
	}

	class var rnsCerulean: UIColor {
		return UIColor(red: 0.0, green: 175.0 / 255.0, blue: 241.0 / 255.0, alpha: 1.0)
	}

	class var rnsWebOrange: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 163.0 / 255.0, blue: 40.0 / 255.0, alpha: 1.0)
	}

	class var rnsMalachite: UIColor {
		return UIColor(red: 0.0, green: 216.0 / 255.0, blue: 98.0 / 255.0, alpha: 1.0)
	}

	class var rnsBlack: UIColor { 
		return UIColor(white: 59.0 / 255.0, alpha: 1.0)
	}
}
