//
//  UIColor+RNSAdditions.swift
//
//  Generated by Zeplin on 11/21/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class var rnsWildStrawberry: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 50.0 / 255.0, blue: 158.0 / 255.0, alpha: 1.0)
	}

	class var rnsCerulean: UIColor {
		return UIColor(red: 0.0, green: 175.0 / 255.0, blue: 241.0 / 255.0, alpha: 1.0)
	}

	class var rnsWebOrange: UIColor {
		return UIColor(red: 255.0 / 255.0, green: 163.0 / 255.0, blue: 40.0 / 255.0, alpha: 1.0)
	}

	class var rnsMalachite: UIColor {
		return UIColor(red: 0.0, green: 216.0 / 255.0, blue: 98.0 / 255.0, alpha: 1.0)
	}

	class var rnsBlack: UIColor { 
		return UIColor(white: 59.0 / 255.0, alpha: 1.0)
	}
    
    class var rnsSokanuRed: UIColor {
        return UIColor(red: 232.0/255.0, green: 63.0/255.0, blue: 47.0/255.0, alpha: 1.0)
    }
    
    class var rnsSwipeCardGreen: UIColor {
        return UIColor(red: 1.0/255.0, green: 216.0/255.0, blue: 89.0/255.0, alpha: 1.0)
    }
    
    class var rnsSwipeCardBlue: UIColor {
        return UIColor(red: 0.0/255.0, green: 173.0/255.0, blue: 244.0/255.0, alpha: 1.0)
    }
    
    class var rnsDarkSkyBlue: UIColor {
        return UIColor(red: 74.0 / 255.0, green: 144.0 / 255.0, blue: 226.0 / 255.0, alpha: 1.0)
    }
    
    class var rnsTomato: UIColor {
        return UIColor(red: 243.0 / 255.0, green: 67.0 / 255.0, blue: 67.0 / 255.0, alpha: 1.0)
    }
    
    class var rnsBlackChat: UIColor {
        return UIColor(red: 72.0 / 255.0, green: 72.0 / 255.0, blue: 72.0 / 255.0, alpha: 1.0)
    }
    
    class var rnsBlueChat: UIColor {
        return UIColor(red: 18.0 / 255.0, green: 169.0 / 255.0, blue: 239.0 / 255.0, alpha: 1.0)
    }
}
